name=SIM800C GSM Shield
version=1.0.0
author=Hiber Bilişim
maintainer=HiberSoft <info@hibersoft.com.tr>
sentence=Arduino UNO + SIM800C GSM Shield kutuphanesi
paragraph=SIM800C modulu ile HTTP, TCP, UDP, MQTT ve SMS (gonderme/alma/okuma/silme/smsPoll) destekler. GPRS baglantisi ve AT komut yonetimi dahildir.
category=Communication
url=https://github.com/hiberblsm/arduino-uno-gsm-shield
architectures=avr
includes=SIM800C.h
depends=SoftwareSerial
